name: initializer
description: A new Flutter module project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.1 <3.0.0'

dependency_overrides:
  analyzer: 5.2.0
  build_resolvers: 2.1.0
  dart_style: 2.2.4

dependencies:
  data:
    path: ../data
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  shared:
    path: ../shared

dev_dependencies:
  dart_code_metrics: 5.1.0
  flutter_lints: 2.0.1
