name: resources
description: A new Flutter module project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.3
  intl: ^0.18.1
  intl_utils: ^2.8.2


flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/src/generated
  arb_dir: lib/src/l10n


