name: app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependency_overrides:
  analyzer: 5.2.0
  build_resolvers: 2.1.0
  dart_style: 2.2.4
dependencies:
  flutter:
    sdk: flutter


  domain:
    path: ../domain
  initializer:
    path: ../initializer
  injectable: 2.1.0
  resources:
    path: ../resources
  rxdart: 0.27.7
  shared:
    path: ../shared
  tuple: 2.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  get_it: ^7.2.0
  
  json_annotation: ^4.8.0
  auto_route: ^5.0.4
  flutter_bloc: ^8.1.2
  google_fonts: ^4.0.3
  hive: ^2.2.3
  path_provider: ^2.0.12
  fluttertoast: ^8.1.2
  flutter_svg: 1.1.6
  flutter_screenutil: 5.5.3+2
  flutter_localizations: 
    sdk: flutter
  intl: ^0.17.0
  salomon_bottom_bar: ^3.3.1
  cached_network_image: ^3.2.3
  lottie: ^2.2.0
  flutter_spinkit: ^5.1.0
  pull_to_refresh: ^2.0.0
  flutter_widget_from_html: ^0.8.5
  image_picker: ^0.8.6+1
  dotted_line: ^3.1.0

  # flutter_html: ^3.0.0-alpha.6
  flutter_markdown: ^0.6.14
  weather: ^2.0.1
  qr_code_scanner: ^1.0.1
  infinite_scroll_pagination: 3.2.0
  collection: ^1.17.0
  grouped_list: ^5.1.2
  device_preview: ^1.1.0
  animated_snack_bar: ^0.3.0
  flutter_staggered_grid_view: ^0.6.2
  # mobile_scanner: ^3.0.0

dev_dependencies:
  auto_route_generator: 5.0.3
  bloc_test: 9.0.3
  build_runner: 2.2.0
  dart_code_metrics: 5.1.0
  flutter_gen_runner: 4.1.6
  flutter_launcher_icons: 0.9.2
  flutter_lints: 2.0.1
  flutter_native_splash: 2.2.16
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  freezed_annotation: 2.2.0
  injectable_generator: 2.1.3
  mocktail: 0.3.0

flutter_gen:
  output: lib/resource/generated
  line_lenght: 160
  null_safety: true

  integrations:
    flutter_svg: true
    lottie: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true
flutter:
  generate: false
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/locale/
    - assets/json/

  
