name: shared
description: A new Flutter module project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.1 <3.0.0'


dependency_overrides:
  analyzer: ^5.12.0
  build_resolvers: ^2.2.0
  dart_style: ^2.3.1


  # sqflite: 2.0.2+1

dependencies:
  async: ^2.11.0
  dartx: ^1.1.0
  decimal: ^2.3.2
  device_info_plus: 9.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  injectable: ^2.1.1
  intl: ^0.18.0
  mime: ^1.0.4
  package_info_plus: 4.0.0
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  timezone: ^0.9.2
  url_launcher: ^6.1.11
  permission_handler: ^10.2.0



dev_dependencies:
  build_runner: ^2.4.4
  dart_code_metrics: ^5.7.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  injectable_generator: ^2.1.5


